In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Japan' 34.0 56000.0]
 ['Singapure' 37.0 38000.0]
 ['China' 20.0 23000.0]
 ['Japan' 33.0 65000.0]
 ['Singapure' 18.0 nan]
 ['China' 28.0 48000.0]
 ['Singapure' nan 43000.0]
 ['Japan' 42.0 74000.0]
 ['China' 40.0 89000.0]
 ['Japan' 35.0 56000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Japan' 34.0 56000.0]
 ['Singapure' 37.0 38000.0]
 ['China' 20.0 23000.0]
 ['Japan' 33.0 65000.0]
 ['Singapure' 18.0 54666.666666666664]
 ['China' 28.0 48000.0]
 ['Singapure' 31.88888888888889 43000.0]
 ['Japan' 42.0 74000.0]
 ['China' 40.0 89000.0]
 ['Japan' 35.0 56000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 34.0 56000.0]
 [0.0 0.0 1.0 37.0 38000.0]
 [1.0 0.0 0.0 20.0 23000.0]
 [0.0 1.0 0.0 33.0 65000.0]
 [0.0 0.0 1.0 18.0 54666.666666666664]
 [1.0 0.0 0.0 28.0 48000.0]
 [0.0 0.0 1.0 31.88888888888889 43000.0]
 [0.0 1.0 0.0 42.0 74000.0]
 [1.0 0.0 0.0 40.0 89000.0]
 [0.0 1.0 0.0 35.0 56000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.2, random_state = 1)

In [46]:
print(x_train)

[[0.0 0.0 1.0 -0.15551452283718187 -0.9765897329107728]
 [0.0 0.0 1.0 -2.124052786598973 -0.2395408778837744]
 [0.0 1.0 0.0 0.1437032932546103 -0.1553067230235458]
 [0.0 1.0 0.0 0.001968538263761343 0.4132738222829959]
 [0.0 0.0 1.0 0.5689075582271571 -1.2924678136366294]
 [0.0 1.0 0.0 1.2775813331814019 0.9818543675895377]
 [1.0 0.0 0.0 0.994111823199704 1.9294886097671073]
 [1.0 0.0 0.0 -0.7067052366904835 -0.6607116521849162]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 20.0 23000.0]
 [0.0 1.0 0.0 35.0 56000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [47]:
print(x_train)

[[0.0 0.0 1.0 -0.15551452283718187 -0.9765897329107728]
 [0.0 0.0 1.0 -2.124052786598973 -0.2395408778837744]
 [0.0 1.0 0.0 0.1437032932546103 -0.1553067230235458]
 [0.0 1.0 0.0 0.001968538263761343 0.4132738222829959]
 [0.0 0.0 1.0 0.5689075582271571 -1.2924678136366294]
 [0.0 1.0 0.0 1.2775813331814019 0.9818543675895377]
 [1.0 0.0 0.0 0.994111823199704 1.9294886097671073]
 [1.0 0.0 0.0 -0.7067052366904835 -0.6607116521849162]]


In [48]:
print(x_test)

[[1.0 0.0 0.0 -1.840583276617275 -2.240102055814199]
 [0.0 1.0 0.0 0.28543804824545926 -0.1553067230235458]]
